### ISSUE TITLE
Can't install decaffeinate properly

### ISSUE THREAD

**Issue by ivanvotti** [eventualbuddha/decaffeinate#1]
OS X Yosemite / node v0.10.35
After `npm install -g decaffeinate` I didn't get `decaffeinate` command:
```
$ which decaffeinate
decaffeinate not found
```
I tried to run it like this `/usr/local/lib/node_modules/decaffeinate/bin/decaffeinate script.coffee` but got an error:

```
/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:114
        throw new Error("unknown node type: " + node.type);
              ^
Error: unknown node type: ForOf
    at traverse (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:114:15)
    at parse (/usr/local/lib/node_modules/decaffeinate/lib/utils/parse.js:21:3)
    at convert (/usr/local/lib/node_modules/decaffeinate/lib/index.js:53:13)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/decaffeinate/lib/cli.js:145:16)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by eventualbuddha** [comment]
Fixed the binary issue in v1.0.2. The other issue of not supporting `for` loops has been noted as #2. I'll add a few words to the README to indicate the status of the project and its goals.
