### ISSUE TITLE
decaffeination attempt failure due to ambigous indentation 

### ISSUE THREAD

**Issue by stefanpenner** [eventualbuddha/decaffeinate#11]
it's possible its an issue on my end, but i figure I would open an issue incase :)

```js
± % cat test/app/lib/data_access/caching_api_clients/crowd_pics_images_spec.coffee|  ./node_modules/.bin/decaffeinate           !10094

/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/node_modules/coffee-script-redux/lib/module.js:60
        throw e;
              ^
Error: Syntax error on line 24: indentation is ambiguous
21 :     }
22 :
23 :     fakeServer = null
24 :     before async(->
^^ :    ^
25 :       fakeServer = sinon.fakeServer.create()
26 :       fakeServer.autoRespond = true
27 :       YB.clientStorage.done ->
    at Preprocessor.Preprocessor.consumeIndentation (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/node_modules
/coffee-script-redux/lib/preprocessor.js:155:17)
    at Preprocessor.Preprocessor.process (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/node_modules/coffee-scr
ipt-redux/lib/preprocessor.js:190:14)
    at Function.Preprocessor.Preprocessor.process (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/node_modules/c
offee-script-redux/lib/preprocessor.js:22:38)
    at CoffeeScript.parse (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/node_modules/coffee-script-redux/lib/m
odule.js:47:35)
    at parse (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/lib/utils/parse.js:22:13)
    at convert (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/lib/index.js:59:13)
    at Socket.<anonymous> (/Users/stefan/src/yapp/projects/yapp-mobile/node_modules/decaffeinate/lib/cli.js:150:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by eventualbuddha** [comment]
Can you provide the file that is failing to parse? Or a smaller subset of it that fails the same way? It's likely that what's happening is CSR is much stricter than the official CS parser and it's bailing when it encounters something bad.

**Comment by stefanpenner** [comment]
@eventualbuddha yes fair, I will attempt a reduce example after work. (if i don't, i have forgotten, you have permission to bug me)

**Comment by eventualbuddha** [comment]
@stefanpenner ping. Also, just released v1.3.0 with support for a few more features.

**Comment by n8agrin** [comment]
@eventualbuddha this should do the trick:

```cs
angular.module('foo', [
    'bar'
  ])
  .config(['$httpProvider', ($httpProvider) ->
    # Set the CSRF (XSRF) header here for all $http requests
    $httpProvider.defaults.xsrfHeaderName = something
  ])

```

**Comment by eventualbuddha** [comment]
Closing this as there's not really much I can do about it without fixing CoffeeScriptRedux itself.
