### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: utf8

### ISSUE THREAD

**Issue by balupton** [eventualbuddha/decaffeinate#21]
Getting this error on bevry/taskgroup:

```
$ decaffeinate src/lib/taskgroup.coffee
fs.js:1613
  options = Object.create(options || {});
                   ^
TypeError: Object prototype may only be an Object or null: utf8
    at Function.create (native)
    at new ReadStream (fs.js:1613:20)
    at fs.createReadStream (fs.js:1602:10)
    at processPath (/Users/balupton/.nvm/versions/io.js/v1.6.1/lib/node_modules/decaffeinate/lib/cli.js:72:19)
    at processNext (/Users/balupton/.nvm/versions/io.js/v1.6.1/lib/node_modules/decaffeinate/lib/cli.js:82:7)
    at runWithPaths (/Users/balupton/.nvm/versions/io.js/v1.6.1/lib/node_modules/decaffeinate/lib/cli.js:88:3)
    at run (/Users/balupton/.nvm/versions/io.js/v1.6.1/lib/node_modules/decaffeinate/lib/cli.js:29:5)
    at Object.<anonymous> (/Users/balupton/.nvm/versions/io.js/v1.6.1/lib/node_modules/decaffeinate/bin/decaffeinate:3:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
```

**Comment by eventualbuddha** [comment]
Thanks for reporting this. Looks like there was a change in iojs that broke the way I was using the `fs` module. Should be fixed in v1.11.1.

**Comment by eventualbuddha** [comment]
I tried v1.11.1 on the file you mentioned and it doesn't work for a few reasons, specifically that CoffeeScriptRedux does not parse the file correctly *and* there are features this project does not yet support, such as binary existential operators (e.g. `a ? b`).

**Comment by balupton** [comment]
Okay no worries, will see what I can do about the file myself. Glad the bug I reported is now fixed! :+1:
