### ISSUE TITLE
Should be able to parse RegExp

### ISSUE THREAD

**Issue by ewiner** [eventualbuddha/decaffeinate#34]
Running `echo "foo = /someregex/i" | decaffeinate` gives the following error:

```
/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:70
    throw new Error('cannot traverse unknown node type: ' + node.type);
          ^
Error: cannot traverse unknown node type: RegExp
    at childPropertyNames (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:70:11)
    at traverse (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:44:47)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:39:9
    at Array.forEach (native)
    at descend (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:30:30)
    at traverse (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:47:5)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:35:11
    at Array.forEach (native)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:33:15
    at Array.forEach (native)
```

As far as I know, regexes in CoffeeScript need no modification to be translated to ES6.

**Comment by eventualbuddha** [comment]
CoffeeScript does have block regular expressions:

```
OPERATOR = /// ^ (
  ?: [-=]>             # function
   | [-+*/%<>&|^!?=]=  # compound assign / compare
   | >>>=?             # zero-fill right shift
   | ([-+:])\1         # doubles
   | ([&|<>])\2=?      # logic / shift
   | \?\.              # soak access
   | \.{2,3}           # range or splat
) ///
```

But they turned out to be fairly easy to handle. This is now supported in v1.17.0. Note that interpolated regexes (e.g. `/foo #{bar} baz/`) are not yet supported.
