### ISSUE TITLE
Error: "Cannot use replaced characters as slice anchors" with `if a then throw Error`

### ISSUE THREAD

**Issue by edi9999** [eventualbuddha/decaffeinate#41]
Hi, with the following source : 

`if a then throw new Error "Error"`

I get the following error : 

```
     Error: Cannot use replaced characters as slice anchors
      at patchThrowStart (src/patchers/patchThrow.js:14:17)
      at src/index.js:30:25
      at traverse (src/utils/traverse.js:28:25)
      at src/utils/traverse.js:23:9
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at src/index.js:81:5
      at traverse (src/utils/traverse.js:28:25)
      at src/utils/traverse.js:19:11
      at Array.forEach (native)
      at src/utils/traverse.js:17:15
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at src/index.js:81:5
      at traverse (src/utils/traverse.js:28:25)
      at src/utils/traverse.js:23:9
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at src/index.js:81:5
      at traverse (src/utils/traverse.js:28:25)
      at convert (src/index.js:60:3)
      at check (test/support/check.js:1:17)
      at Context.<anonymous> (test/decaffeinate_test.js:399:7)
```

**Comment by eventualbuddha** [comment]
These sorts of things are usually an order-of-operations issue. Adding some debugging to MagicString, I see this happening:

```
$ echo 'if a then throw new Error "Error"' | ./bin/decaffeinate
INSERT 3 "("
OVERWRITE 5...10 "then " => ""
INSERT 4 ") {"
```

It looks like what's happening is that it's removing the `then` and then inserting the `) {` as distinct steps when they probably should be combined in [`patchConditionalEnd`](https://github.com/eventualbuddha/decaffeinate/blob/5639c745b9076083a22d700cd67880a289b9de17/src/patchers/patchConditional.js#L70-L83):

```js
if (!replaceBetween(patcher, node, node.parentNode.consequent, 'then ', '')) {
  replaceBetween(patcher, node, node.parentNode.consequent, 'then', '');
}
let parens = isSurroundedBy(node, '(', patcher.original);
let inserted = parens ? ' {' : ') {';
if (isUnlessConditional(node.parentNode, patcher.original) && requiresParentheses(node.expression)) {
  inserted = `)${inserted}`;
}
let nodeRange = trimmedNodeRange(node, patcher.original);
patcher.insert(nodeRange[1] + (parens ? ')'.length : 0), inserted);
```

If you care to make a PR to fix it I'd be happy to review!

**Comment by eventualbuddha** [comment]
This seems to be [fixed](http://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=true&code=if%20a%20then%20throw%20new%20Error%20%22Error%22) in the latest version.
