### ISSUE TITLE
Simple if condition with `and` fails

### ISSUE THREAD

**Issue by edi9999** [eventualbuddha/decaffeinate#42]
`if (a? and a!="") then 1`

fails with 

```
     Error: BUG! Could not fix range for NEQOp because it has no raw value
      at fixRange (src/utils/parse.js:70:13)
      at src/utils/parse.js:19:5
      at traverse (src/utils/traverse.js:28:25)
      at src/utils/traverse.js:23:9
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at traverse (src/utils/traverse.js:35:5)
      at src/utils/traverse.js:23:9
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at traverse (src/utils/traverse.js:35:5)
      at src/utils/traverse.js:19:11
      at Array.forEach (native)
      at src/utils/traverse.js:17:15
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at traverse (src/utils/traverse.js:35:5)
      at src/utils/traverse.js:23:9
      at Array.forEach (native)
      at descend (src/utils/traverse.js:14:30)
      at traverse (src/utils/traverse.js:35:5)
      at parse (src/utils/parse.js:17:3)
      at convert (src/index.js:40:15)
      at check (test/support/check.js:1:17)
      at Context.<anonymous> (test/decaffeinate_test.js:403:7)
```

**Comment by eventualbuddha** [comment]
Closed by #44.
