### ISSUE TITLE
Error: cannot traverse unknown node type: InOp

### ISSUE THREAD

**Issue by jgebhardt** [eventualbuddha/decaffeinate#52]
To repro, run: 

`curl -s https://raw.githubusercontent.com/atom/atom/b682658427eb9edb5cf9b152652817a8305bf43e/src/package-manager.coffee | decaffeinate | less`

```
/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:148
    throw new Error('cannot traverse unknown node type: ' + node.type);
          ^
Error: cannot traverse unknown node type: InOp
    at childPropertyNames (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:148:11)
    at traverse (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:36:47)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:31:9
    at Array.forEach (native)
    at descend (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:22:32)
    at traverse (/usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:39:5)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:27:11
    at Array.forEach (native)
    at /usr/local/lib/node_modules/decaffeinate/lib/utils/traverse.js:25:15
    at Array.forEach (native)
```

Version: decaffeinate@1.33.4

**Comment by eventualbuddha** [comment]
Fixed in v1.34.0. Thanks for reporting!

**Comment by eventualbuddha** [comment]
Note that there are still problems processing that file, but `InOp` e.g. `a in b` now works.

**Comment by eventualbuddha** [comment]
I fixed the remainder of the errors I encountered in that file in v1.35.0. It still isn't perfect because of this:

```coffee
@deactivatePackage(packageName) for packageName in packagesToDisable when @getActivePackage(packageName)
```

Which gets turned into this:

```js
for (var i = 0, packageName; i < packagesToDisable.length; i++) { when this.getActivePackage(packageName)
  packageName = packagesToDisable[i];
  this.deactivatePackage(packageName);
}
```

That is, the `when` part is not yet handled. I've created #53 to track it.
