### ISSUE TITLE
Error always reports line 1

### ISSUE THREAD

**Issue by blimmer** [eventualbuddha/decaffeinate#54]
It would be nice if the parser reported the line that it choked on. For instance, given this file
```coffeescript
# random comment

foo = func('param',
  bar: 'baz'
  qux: 'im out of things'
)
```

it doesn't match CoffeeScript redux format, so it bails with this message:
```
› decaffeinate test.coffee
/Users/blimmer/.nvm/versions/node/v0.12.5/lib/node_modules/decaffeinate/node_modules/coffee-script-redux/lib/module.js:61
      throw new Error(formatParserError(preprocessed, e));
            ^
Error: Syntax error on line 1, column 1: unexpected '\n' (\u000A)
1 : # random comment
^ : ^
2 :
3 : foo = func('param',
4 :   bar: 'baz'
    at CoffeeScript.parse (/Users/blimmer/.nvm/versions/node/v0.12.5/lib/node_modules/decaffeinate/node_modules/coffee-script-redux/lib/module.js:61:13)
    at parse (/Users/blimmer/.nvm/versions/node/v0.12.5/lib/node_modules/decaffeinate/lib/utils/parse.js:36:42)
    at convert (/Users/blimmer/.nvm/versions/node/v0.12.5/lib/node_modules/decaffeinate/lib/index.js:177:43)
    at ReadStream.<anonymous> (/Users/blimmer/.nvm/versions/node/v0.12.5/lib/node_modules/decaffeinate/lib/cli.js:106:35)
    at ReadStream.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

which makes it hard to figure out what I need to change to make `decaffeinate` work. With large files, I like to correct to CoffeeScript redux format and let `decaffeinate` do the heavy lifting.

It seems like this would be possible, because the CoffeeScript Redux web parser is able to identify the place where the parsing problem exists:

![screen shot 2015-09-10 at 4 28 47 pm](https://cloud.githubusercontent.com/assets/630449/9981741/a997c864-5f82-11e5-9266-6cafc093f2f7.png)

**Comment by eventualbuddha** [comment]
@blimmer thanks for the report. It appears this was a bug in CoffeeScriptRedux and has been fixed on master. If you re-install decaffeinate (and perhaps explicitly remove CoffeeScriptRedux too?) it should work as expected.

**Comment by blimmer** [comment]
Confirm this is fixed!
