### ISSUE TITLE
Error: cannot traverse unknown node type: UnsignedRightShiftOp

### ISSUE THREAD

**Issue by alexgorbatchev** [eventualbuddha/decaffeinate#80]
```coffeescript
module.exports = (model, calc) ->
  fn = (buf, previous) -> calc(buf, previous) >>> 0
  fn.signed = calc
  fn.unsigned = fn
  fn.model = model

  fn
```

results in the following error using `1.40.16`

```
Error: cannot traverse unknown node type: UnsignedRightShiftOp
    at childPropertyNames (.../decaffeinate/dist/decaffeinate.cjs.js:571:11)
    at traverse (.../decaffeinate/dist/decaffeinate.cjs.js:473:47)
    at .../decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (.../decaffeinate/dist/decaffeinate.cjs.js:459:32)
    at traverse (.../decaffeinate/dist/decaffeinate.cjs.js:476:5)
    at .../decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (.../decaffeinate/dist/decaffeinate.cjs.js:459:32)
    at traverse (.../decaffeinate/dist/decaffeinate.cjs.js:476:5)
```

**Comment by eventualbuddha** [comment]
Fixed in v1.40.17.
