### ISSUE TITLE
Multiple `or` statements do not work

### ISSUE THREAD

**Issue by netei** [eventualbuddha/decaffeinate#83]
With the following file : 

```
t=true || false || true
```

gives the following error : 

```
~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:792
      throw new Error('BUG! Could not fix range for ' + node.type + ' because
            ^
Error: BUG! Could not fix range for LogicalOrOp because it has no raw value
    at fixRange (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:792:13)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:723:5
    at traverse (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:473:23)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:459:32)
    at traverse (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:476:5)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:459:32)
```
Using 1.40.17

**Comment by eventualbuddha** [comment]
Fixed in v1.40.18.
