### ISSUE TITLE
Does not work with chained methods

### ISSUE THREAD

**Issue by netei** [eventualbuddha/decaffeinate#85]
```
obj
	.m1()
	.m2()
```

fails with 

```
~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:813
    throw new Error('BUG! Could not fix range for ' + node.type + ' at line '
          ^
Error: BUG! Could not fix range for FunctionApplication at line 1, column 1
    at fixRange (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:813:11)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:723:5
    at traverse (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:473:23)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:459:32)
    at traverse (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:476:5)
    at ~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:468:9
    at Array.forEach (native)
    at descend (~/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:459:32)
```

**Comment by eventualbuddha** [comment]
I believe this is a dup of #51.

**Comment by netei** [comment]
Ok
