### ISSUE TITLE
Herestring doesnt do interpolation when they are quotes

### ISSUE THREAD

**Issue by netei** [eventualbuddha/decaffeinate#99]
Input : 

```
a="""
bar="#{bar}"
"""
```

Gives the following error : 

```
Error: Cannot overwrite the same content twice: '#'                                                                   
    at MagicString.overwrite (/home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/node_modules/
magic-string/dist/magic-string.cjs.js:470:10)                                                                         
    at patchLineComment (/home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.
cjs.js:1613:11)                                                                                                       
    at /home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:1591:9     
    at Array.forEach (native)                                                                                         
    at patchComments (/home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs
.js:1588:10)                                                                                                          
    at convert (/home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:50
55:3)                                                                                                                 
    at ReadStream.<anonymous> (/home/ldap/hipped/.nvm/versions/node/v0.12.7/lib/node_modules/decaffeinate/dist/decaffe
inate.cjs.js:4942:16)                                                                                                 
    at ReadStream.emit (events.js:129:20)                                                                             
    at _stream_readable.js:908:16                                                                                     
    at process._tickCallback (node.js:355:11)
```

**Comment by eventualbuddha** [comment]
Fixed in v1.41.3.
